import { all, get, run } from '../db.js';
import { leaderboard } from './metrics.js';
import { retrievalOverlay } from './serp.js';
import { round } from '../util/stats.js';

/**
 * §69 — alerting.
 *
 * Alerts are generated by comparing the current state against the most recent
 * stored snapshot (§55), so every alert is a statement about a change we
 * actually observed between two dated measurements, not a threshold crossed in
 * the abstract. An alert nobody can trace back to two numbers is noise.
 */

export function generateAlerts(entityId, { now = Date.now() } = {}) {
  const board = leaderboard(entityId, { now });
  if (!board) return [];

  const previous = get(
    `SELECT * FROM entity_snapshots WHERE entity_id = ? ORDER BY captured_at DESC LIMIT 1`,
    entityId
  );
  let priorByAssociation = new Map();
  if (previous) {
    try {
      const payload = JSON.parse(previous.payload);
      priorByAssociation = new Map((payload.associations ?? []).map((a) => [a.association_id, a]));
    } catch {
      // A malformed snapshot is not a reason to skip alerting entirely.
    }
  }

  const created = [];
  const emit = (alert) => {
    const res = run(
      `INSERT INTO alerts (entity_id, association_id, kind, severity, headline, detail, payload)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      entityId,
      alert.association_id ?? null,
      alert.kind,
      alert.severity,
      alert.headline,
      alert.detail ?? null,
      JSON.stringify(alert.payload ?? {})
    );
    created.push({ id: Number(res.lastInsertRowid), ...alert });
  };

  for (const row of board.associations) {
    const prior = priorByAssociation.get(row.association_id);

    // New negative association with real corroboration behind it. The domain
    // threshold is what keeps a single hostile blog from raising an alarm.
    if (!prior && row.sentiment.label === 'negative' && row.domains >= 3) {
      emit({
        association_id: row.association_id,
        kind: 'new_negative',
        severity: row.domains >= 8 ? 'critical' : 'warning',
        headline: `A new association "${row.label}" has appeared across ${row.domains} independent domains.`,
        detail: `Current PIAS ${row.current_pias}, ${row.documents} documents, sentiment ${round((row.sentiment.negative ?? 0) * 100, 0)}% negative.`,
        payload: { current_pias: row.current_pias, domains: row.domains, documents: row.documents },
      });
    }

    if (prior) {
      const shareNow = (row.current_corpus_share ?? 0) * 100;
      const sharePrior = (prior.current_corpus_share ?? 0) * 100;
      if (shareNow - sharePrior >= 8) {
        emit({
          association_id: row.association_id,
          kind: 'rapid_growth',
          severity: 'info',
          headline: `"${row.label}" current share increased from ${round(sharePrior, 0)}% to ${round(shareNow, 0)}%.`,
          detail: `Momentum ${row.momentum.arrow} ${row.momentum.label}.`,
          payload: { from: round(sharePrior, 2), to: round(shareNow, 2) },
        });
      }

      // Historical resurgence: something that had been decaying picks up new
      // independent sources. This is the alert ORM work exists to catch early.
      const domainGain = row.domains - (prior.domains ?? 0);
      if (domainGain >= 5 && prior.momentum_bucket && ['down', 'rapid_down'].includes(prior.momentum_bucket)) {
        emit({
          association_id: row.association_id,
          kind: 'resurgence',
          severity: row.sentiment.label === 'negative' ? 'critical' : 'warning',
          headline: `"${row.label}" had been declining but gained ${domainGain} new independent domains since the last snapshot.`,
          detail: `Current PIAS moved from ${prior.current_pias ?? '—'} to ${row.current_pias}.`,
          payload: { domain_gain: domainGain, previous_bucket: prior.momentum_bucket },
        });
      }

      const grsNow = row.google_retrieval_score ?? null;
      const grsPrior = prior.google_retrieval_score ?? null;
      if (grsNow !== null && grsPrior !== null && Math.abs(grsNow - grsPrior) >= 10) {
        emit({
          association_id: row.association_id,
          kind: 'serp_convergence',
          severity: 'info',
          headline: `Google SERP association share for ${row.label} ${grsNow > grsPrior ? 'increased' : 'decreased'} ${Math.abs(round(grsNow - grsPrior, 0))} points.`,
          detail: `From ${grsPrior} to ${grsNow} on the entity query.`,
          payload: { from: grsPrior, to: grsNow },
        });
      }
    }
  }

  return created;
}

/**
 * §55 — the weekly row. Stored whether or not anything changed, because the
 * absence of change is itself the measurement the correlation study needs.
 */
export function storeSnapshot(entityId, { now = Date.now(), coverage = null } = {}) {
  const board = leaderboard(entityId, { now });
  if (!board) return null;
  const overlay = retrievalOverlay(entityId);

  const payload = {
    generated_at: board.generated_at,
    entity_documents: board.entity_documents,
    current_entity_documents: board.current_entity_documents,
    serp_snapshot_at: overlay?.snapshot?.captured_at ?? null,
    associations: board.associations.map((a) => ({
      association_id: a.association_id,
      label: a.label,
      pias: a.pias,
      current_pias: a.current_pias,
      historical_pias: a.historical_pias,
      corpus_share: a.corpus_share,
      current_corpus_share: a.current_corpus_share,
      google_retrieval_score: a.google_retrieval_score,
      documents: a.documents,
      domains: a.domains,
      momentum_bucket: a.momentum.bucket,
      momentum_basis: a.momentum.basis,
      sentiment: a.sentiment.label,
    })),
  };

  const res = run(
    `INSERT INTO entity_snapshots (entity_id, coverage, payload) VALUES (?, ?, ?)`,
    entityId,
    JSON.stringify(coverage ?? {}),
    JSON.stringify(payload)
  );
  return { snapshot_id: Number(res.lastInsertRowid), associations: payload.associations.length };
}

export const listAlerts = (entityId, { includeAcknowledged = false, limit = 100 } = {}) =>
  all(
    `SELECT a.*, s.canonical_label AS association_label
       FROM alerts a LEFT JOIN associations s ON s.id = a.association_id
      WHERE a.entity_id = ? AND (? = 1 OR a.acknowledged = 0)
      ORDER BY a.created_at DESC, a.id DESC LIMIT ?`,
    entityId,
    includeAcknowledged ? 1 : 0,
    limit
  );

export const acknowledgeAlert = (alertId) =>
  run(`UPDATE alerts SET acknowledged = 1 WHERE id = ?`, alertId);

/**
 * §55 — the correlation read-out. Deliberately descriptive: with a handful of
 * weekly snapshots there is nothing to fit, and presenting a model here would
 * be exactly the false precision §56 warns against. It reports the series and
 * says how much data would be needed before the question can be asked.
 */
export function snapshotSeries(entityId) {
  const snapshots = all(
    `SELECT id, captured_at, payload FROM entity_snapshots WHERE entity_id = ? ORDER BY captured_at`,
    entityId
  );
  const series = snapshots.map((s) => {
    let payload = {};
    try { payload = JSON.parse(s.payload); } catch { /* skip malformed */ }
    return { id: s.id, captured_at: s.captured_at, associations: payload.associations ?? [] };
  });
  return {
    count: series.length,
    series,
    ready_for_correlation: series.length >= 8,
    note:
      series.length >= 8
        ? 'Enough snapshots to begin looking for lead/lag relationships between corpus movement and Google retrieval.'
        : `${series.length} of a suggested minimum 8 weekly snapshots. Until then this is a record, not a model.`,
  };
}
